AWSでWEBコンソールを使わずにpython使ってVPCを作成しようとしたら以下のエラー発生

AWS was not able to validate the provided access credentials

credentials情報やリージョン情報を確認したけど問題なし。
ググったら時刻がズレすぎているとエラーになるんですね。
自宅サーバーから実行していたので見てみたら10分ほどずれていた。
時刻を同期したら直った。

■参考URL
https://tech.royozaki.net/tech/jp/awscrederr.html
https://qiita.com/iam_nk/items/7acdd5e67d4a5c9ce6e2